### ISSUE TITLE
Cant disable modules, where to set map time limit?

### ISSUE THREAD

**Issue by Reeley** [EvoTM/EvoSC#55]
Hey first of all great piece of software you guys open sourced. Thanks for that.

I have a few problems, first i dont know how to disable modules. I tried to disable the donations module by changing enabled to false in its config (core/Modules/Donations/donations.config.json) but this has no effect and the donation UI is still rendered. Same for the Pay2Play widget.

Secondly i have no idea where to put the timelimit for the round time. I added <timeattack_limit>360000</timeattack_limit> to the  tracklist file. But when starting EvoSC it says that there is no time defined and it will use the default time, which is 10 minutes.

**Comment by brakerb** [comment]
You changed the default config, you need to change donations.config.json inside `base_dir/config`.

The timelimit is defined in your match-settings. See https://doc.maniaplanet.com/dedicated-server/references/settings-list-for-nadeo-gamemodes for all possible settings. `S_TimeLimit` is what you're looking for.
Add `<setting name="S_TimeLimit" type="integer" value="900"/>` to `<script_settings></script_settings>`

In the future you'll be able to change it ingame. You can already, but I discourage to use it atm because it is buggy and may corrupt some configs, but if you want to try type //config in the chat.

**Comment by Reeley** [comment]
Ok seemed wrong anyways to change files in core^^ Now it works thanks. Kind of hard to get a overview without any docs. Will 1.0 feature some doc sites?

**Comment by brakerb** [comment]
Yes a proper installation guide will be made before official release and a code-documentation is also planned.
