### ISSUE TITLE
Please fix MX functions and maniakarma

### ISSUE THREAD

**Issue by BestNoob** [EvoTM/EvoSC#90]
https://api.mania-exchange.com/documents/reference
Did u recognized that they´ve updated the stuff for TM20 ? TM.MX etc. ? So it should be doable to FIX maniakarma, and the add MAP function

**Comment by snixtho** [comment]
The reason the map adding function is broken is because TMX just changed their API lately. But this was already fixed 5 days ago: f8747746779cade17f4e5b746db4891bf393dfb9

Also, I don't think TMX implemented mx karma for TM2020 yet, so we cant enable it. But if you enable it in the config `mx-karma.config.json` you will have a local solution.

**Comment by brakerb** [comment]
As snix mentioned, it should be fixed in the develop branch, which will soon be merged with amster again.
Also please use the issue templates if possible and if not at least include the EvoSC version you run. It is written in the VERSION file or if you call /version on the server.
